# Generated by Django 4.0.3 on 2022-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='id',
        ),
        migrations.AlterField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
