# Generated by Django 4.0.3 on 2022-04-20 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_remove_problem_id_alter_problem_problem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('code', models.CharField(max_length=3000)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='signup.problem', verbose_name='problem_id')),
                ('verdict', models.CharField(max_length=20)),
                ('time', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('input', models.CharField(max_length=200)),
                ('output', models.CharField(max_length=200)),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='signup.problem', verbose_name='problem_id')),
            ],
        ),
    ]
