# Generated by Django 4.0.3 on 2022-04-20 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_solution_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='signup.problem', verbose_name='problem_id'),
        ),
    ]
